# Generated by Django 6.0.6 on 2026-06-30 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('employee_created', 'Employee Created'), ('employee_updated', 'Employee Updated'), ('employee_deleted', 'Employee Deleted'), ('leave_submitted', 'Leave Submitted'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('leave_cancelled', 'Leave Cancelled'), ('salary_updated', 'Salary Updated'), ('payroll_processed', 'Payroll Processed'), ('announcement_created', 'Announcement Created'), ('attendance_marked', 'Attendance Marked'), ('department_created', 'Department Created'), ('department_updated', 'Department Updated'), ('department_deleted', 'Department Deleted'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
